// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh0SNbO10q4GVdV9tL9tGBxNtbMv4tIac',
    appId: '1:360117664704:web:34f0f764b63b36b55fa625',
    messagingSenderId: '360117664704',
    projectId: 'to-do-list-app-658a2',
    authDomain: 'to-do-list-app-658a2.firebaseapp.com',
    storageBucket: 'to-do-list-app-658a2.firebasestorage.app',
    measurementId: 'G-T1JSS5QHTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiTTyQJC4s3CRyqiXV8XJFR3E0Rq1vjDo',
    appId: '1:360117664704:android:df827ce25740bfd65fa625',
    messagingSenderId: '360117664704',
    projectId: 'to-do-list-app-658a2',
    storageBucket: 'to-do-list-app-658a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ21eZXTNVGg6X9c9dpbUnqAy2aUWhdnY',
    appId: '1:360117664704:ios:520b1cf4136ff9ac5fa625',
    messagingSenderId: '360117664704',
    projectId: 'to-do-list-app-658a2',
    storageBucket: 'to-do-list-app-658a2.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ21eZXTNVGg6X9c9dpbUnqAy2aUWhdnY',
    appId: '1:360117664704:ios:520b1cf4136ff9ac5fa625',
    messagingSenderId: '360117664704',
    projectId: 'to-do-list-app-658a2',
    storageBucket: 'to-do-list-app-658a2.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh0SNbO10q4GVdV9tL9tGBxNtbMv4tIac',
    appId: '1:360117664704:web:c869b026bef4f07f5fa625',
    messagingSenderId: '360117664704',
    projectId: 'to-do-list-app-658a2',
    authDomain: 'to-do-list-app-658a2.firebaseapp.com',
    storageBucket: 'to-do-list-app-658a2.firebasestorage.app',
    measurementId: 'G-VKX4CT3W0T',
  );
}
